title: Jenny Li
#author: Author
#email: your-email@example.com
description: welcome to my world

# github_username:  aidewoode
# twitter_username:
facebook_username: jennyli1340
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
