title: Jenny Li
author: Jenny Li
email: jennyli1340@gmail.com
description: welcome to my world

# github_username:  aidewoode
# twitter_username:
facebook_username: jennyli1340
linkedin_username: lijenny1
instagram_username: donttreadonli
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
